In [ ]:
Python library is a collection of functions and methods that allows us to perform many actons without any codes.
For numerical computations = NumPy
For visualizaion = matplotlib, seaborn, plotly etc.
For data manipulation = pandas
For implement machine learning algorithm = scikit-learn 
For deep learning = tensorflows and keras

PURPOSE OF LIBRARY

Not write the code from entire beginning ,it will automatically provide some inbuilt functions which we can use to make our work even more easier.

In [ ]:
NumPy

Stands for Numerical Python and is the core library for numerical and scientific computing. It provide a multidimensional array object and 
a collection of routines for processing arrays.

In [ ]:
#1 d array#

In [ ]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#2d array#

In [ ]:
import numpy as np
n1=np.array([[12,34,56],[67,98,90]])
n1

array([[12, 34, 56],
       [67, 98, 90]])

In [ ]:
#zeros

In [ ]:
"""initializing numpy arrays
1 dimensional arrays"""

In [ ]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
import numpy as np
n1=np.zeros((5,3)) #5 denotes rows and 3 denotes columns 
n1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#same number

In [ ]:
import numpy as np
n1=np.full ((2,5),10)#2 denotes rows and 5 denotes columns and 10 denote the value 
n1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
# Random number

In [ ]:
import numpy as np 
n1=np.random .randint (10,20,6) #output no.s are within 10 to 20 and provide 6 numbers.Randint is the submethod.

n1

array([18, 19, 11, 10, 10, 18])

In [ ]:
# Checking the shape

In [ ]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6],[6,9,7]])
n1.shape

(3, 3)

In [ ]:
"""Joining Numpy Arrays
1.vstack().........vertically stack
2.hstack()...........horizondally stack/head stack
3.column_stack()"""


In [ ]:
#vstack()

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([20,90,60])
n3=np.array([30,75,87])
np.vstack((n1,n2,n3))

array([[10, 20, 30],
       [20, 90, 60],
       [30, 75, 87]])

In [ ]:
#hstack()

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([20,90,60])
np.hstack((n1,n2))

array([10, 20, 30, 20, 90, 60])

In [ ]:
#column_stack()

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([20,90,60])
np.column_stack((n1,n2))

array([[10, 20],
       [20, 90],
       [30, 60]])

In [ ]:
# numpy intersection ...to find the common elements in arrays

In [ ]:
import numpy as np
n1=np.array([10,45,62])
n2=np.array([10,65,78])
np.intersect1d(n1,n2)

array([10])

In [ ]:
# numpy difference.....to find elements present in one particular array not in another

In [ ]:
import numpy as np
n1=np.array([10,15,20,25])
n2=np.array([15,20])
np.setdiff1d(n1,n2)

array([10, 25])

In [ ]:
# ADDITION OF NUMPY ARRAYS

In [ ]:
# case 1

In [ ]:
import numpy as np
n1=np.array([10,15,60])
n2=np.array([5,20,12])
np.sum([n1,n2])        #...10+15+60+5+20+12 = 122

122

In [ ]:
# case 2 ......vertical addition

In [ ]:
import numpy as np
n1=np.array([25,15,10])
n2=np.array([5,25,18])
np.sum([n1,n2],axis = 0) #....25+5 ,15+25, 10+18

array([30, 40, 28])

In [ ]:
#case 3......horizondal addition

In [ ]:
import numpy as np
np.sum([[0, 1], [0, 5]], axis=1) #0+0, 1+5

array([1, 5])

In [ ]:
# BASIC NUMPY MATHEMATICS

In [ ]:
# Addition

In [ ]:
import numpy as np
n1 = np.array([24,89,65])         # 24+14 ,89+14 ,65+14
sum= n1+14
sum

array([ 38, 103,  79])

In [ ]:
# Subtraction

In [ ]:
import numpy as np
n1 = np.array([76,39,83])     # 76-20 ,39-20 ,83-20
sub=n1-20
sub

array([56, 19, 63])

In [ ]:
# Multiplication

In [ ]:
import numpy as np
n1 = np.array([36,81,15.5])     #  36*3 ,81*3 ,15.5*3
mul=n1*3
mul

array([108. , 243. ,  46.5])

In [ ]:
# Division

In [ ]:
import numpy as np
n1 = np.array([28.6,57,69])     #  28.6/5 ,57/5 ,69/5
div=n1/5
div

array([ 5.72, 11.4 , 13.8 ])

In [ ]:
 # NUMPY MATH FUNCTIONS

In [ ]:
# Mean

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [ ]:
# Median

In [ ]:
import numpy as np
n1=np.array([11,58,69,32,45,25,74])
np.median(n1)

45.0

In [ ]:
# Standard Deviation

In [ ]:
import numpy as np
n1=np.array ([45,258,30,45,76,47])
np.std(n1)

79.23120176630752